export {default as Login} from './components/login/manager/Login'
// export {default as Accounts} from './components/Accounts'
export {default as Prices} from './components/Prices'
export {default as Welcome} from './components/welcome/manager/Welcome'
export {default as Wallet} from './components/wallet/Wallet'
export {default as Home} from './components/wallet/Home'
export {default as ManageAccounts} from './components/wallet/manager/ManageAccounts'
export {default as Profile} from './components/wallet/manager/Profile'
export {default as Dashboard} from './components/wallet/manager/Dashboard'
export {default as Balances} from './components/wallet/manager/Balances'
export {default as Transactions} from './components/wallet/manager/Transactions'
